name = "voidspace"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

assets = { directory = ".open-next/assets", binding = "ASSETS" }

[[d1_databases]]
binding = "DB"
database_name = "voidspace-db"
database_id = "29eb8bfd-7dd7-4802-985d-04d583236b26"

[[r2_buckets]]
binding = "R2"
bucket_name = "voidspace-media"

[vars]
JWT_SECRET = "change-this-in-production"
